openapi: 3.1.0
info:
  title: Area API - OpenAPI 3.1
  description: |-
    This is the doc for the Area Project based on the OpenAPI 3.1 specification.  You can find out more about
    the project at [https://github.com/Flagada2000](https://github.com/Flagada2000).

    Some useful links:
    - [The Area repository](https://github.com/orgs/Flagada2000/repositories)

  version: 1.0.1

tags:
  - name: Auth
    description: Everything about Authentication
paths:
  /auth/signin:
    post:
      tags:
      - Auth
      summary: Connexion de l'utilisateur
      description: Permet aux utilisateurs de se connecter en utilisant leur email et mot de passe.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  examples: [utilisateur@example.com]
                password:
                  type: string
                  format: password
                  examples: [motdepasse123]
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '401':
          description: Authentification échouée
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "Email ou mot de passe incorrect"
        '500':
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Erreur serveur"
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Inscription de l'utilisateur
      description: Permet aux nouveaux utilisateurs de créer un compte en utilisant leur email et mot de passe.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  examples: [nouvelutilisateur@example.com]
                password:
                  type: string
                  format: password
                  minLength: 6
                  examples: [nouveaumotdepasse123]
      responses:
        '201':
          description: Inscription réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '400':
          description: Données invalides fournies
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Email ou mot de passe invalide"
        '500':
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Erreur serveur"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        email_confirmed_at:
          type: string
          format: date-time
        phone:
          type: string
          format: phone
        phone_confirmed_at:
          type: string
          format: date-time
        last_sign_in_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Session:
      type: object
      properties:
        access_token:
          type: string
          format: jwt
        token_type:
          type: string
          enum: [bearer]
        expires_in:
          type: integer
          format: int32
          description: Durée de validité du token en secondes
        refresh_token:
          type: string
          format: jwt
        user:
          $ref: '#/components/schemas/User'
