openapi: 3.1.0
info:
  title: Area API - OpenAPI 3.1
  description: |-
    This is the doc for the Area Project based on the OpenAPI 3.1 specification.  You can find out more about
    the project at [https://github.com/Flagada2000](https://github.com/Flagada2000).

    Some useful links:
    - [The Area repository](https://github.com/orgs/Flagada2000/repositories)

  version: 1.0.1

tags:
  - name: Auth
    description: Everything about Authentication
paths:
  /auth/signin:
    post:
      tags:
      - Auth
      summary: Connexion de l'utilisateur
      description: Permet aux utilisateurs de se connecter en utilisant leur email et mot de passe.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  examples: [utilisateur@example.com]
                password:
                  type: string
                  format: password
                  examples: [motdepasse123]
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '401':
          description: Authentification échouée
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "Email ou mot de passe incorrect"
        '500':
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Erreur serveur"
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Inscription de l'utilisateur
      description: Permet aux nouveaux utilisateurs de créer un compte en utilisant leur email et mot de passe.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  examples: [nouvelutilisateur@example.com]
                password:
                  type: string
                  format: password
                  minLength: 6
                  examples: [nouveaumotdepasse123]
      responses:
        '201':
          description: Inscription réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '400':
          description: Données invalides fournies
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Email ou mot de passe invalide"
        '500':
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Erreur serveur"
  /auth/me:
    get:
      tags:
      - Auth
      summary: Get user information
      description: Retrieves the current user's information based on the access token.
      responses:
        '200':
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 401
                  message:
                    type: string
                    example: "No access token found"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "An unexpected error occurred"
    /actions/create:
    post:
      tags:
      - Actions
      summary: Create a new user action
      description: Allows authenticated users to create a new action.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserActionDto'
      responses:
        '201':
          description: Action created successfully
        '401':
          description: Unauthorized access
        '500':
          description: Server error

  /actions/update:
    patch:
      tags:
      - Actions
      summary: Update a user action
      description: Allows authenticated users to update an existing action.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserActionDto'
      responses:
        '200':
          description: Action updated successfully
        '401':
          description: Unauthorized access
        '500':
          description: Server error

  /actions/delete:
    delete:
      tags:
      - Actions
      summary: Delete a user action
      description: Allows authenticated users to delete an existing action.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Action deleted successfully
        '401':
          description: Unauthorized access
        '500':
          description: Server error

  /actions/user:
    get:
      tags:
      - Actions
      summary: Retrieve user's actions
      description: Retrieves all actions associated with the authenticated user.
      responses:
        '200':
          description: Actions retrieved successfully
        '401':
          description: Unauthorized access
        '500':
          description: Server error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        email_confirmed_at:
          type: string
          format: date-time
        phone:
          type: string
          format: phone
        phone_confirmed_at:
          type: string
          format: date-time
        last_sign_in_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    CreateUserActionDto:
      type: object
      required:
        - action_id
        - action_config
      properties:
        action_id:
          type: integer
        action_config:
          type: string
    UpdateUserActionDto:
      type: object
      required:
        - id
        - action_id
        - action_config
      properties:
        id:
          type: integer
        action_id:
          type: integer
        action_config:
          type: string
    Session:
      type: object
      properties:
        access_token:
          type: string
          format: jwt
        token_type:
          type: string
          enum: [bearer]
        expires_in:
          type: integer
          format: int32
          description: Durée de validité du token en secondes
        refresh_token:
          type: string
          format: jwt
        user:
          $ref: '#/components/schemas/User'
